### ISSUE TITLE
Midpoint: To document meaning of Reconcile checkbox at User Form.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#106]
I created and edited several users. Sometime I saved without Reconcile check box and everything was ok. What is exact meaning of this check box? Pls give to me maximum of info about it.

**Comment by katkav** [comment]
You do not need to check reconcile if you create new user. You only need it in special cases, e.g. something went wrong (some of the resource was offline while the accounts were created etc) and you want to fix problems. But in normal cases, you just need to create a user and click save button, nothing more.

**Comment by skrchnavy** [comment]
Based on the answer I expect this shall be properly mentioned in the documentation of ODN. Also with a link to Midpoint if such available

**Comment by skrchnavy** [comment]
Documentation issue.

**Comment by hanecak** [comment]
In an attempt to clean-up our backlog, I'm closing this as "wont fix" given that bug is truly old (we're supporting only most recent minor release, i.e. as of ODN 1.2.5, we're supporting 1.2.x, not older).

Having said that, whoever is negatively affected by this again in the future, please reopen this.

Note: IIRC "reconcile" is no longer needed in usual ODN installation process, so this is truly low priority).
