### ISSUE TITLE
Private and deleted dataset is visible in public catalog.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#110]
I created dataset as private. Saved. Is visible in IC but not in PC.
I edited this dataset and changed visibility to public.  Is visible in IC and also in PC.
I edited this dataset and changed visibility back to private. Is visible in IC and also in PC.

The same bad behaviour is if I delete dataset in internal catalog.
ODN-27:Publicly available catalog records search using keywords
ODN-26:Publicly available catalog record browser
ODN-28:Publicly available catalog records filtering
ODN-19:Make dataset publicly invisible

**Comment by skrchnavy** [comment]
@OskarStoffan shall be such dataset removed from PC?

**Comment by OskarStoffan** [comment]
According to user story sto_12 yes, however this is not what we want to achieve as final implementation. Termination of maintenance/publication of a dataset in accordance with methodology defined should be implemented differently - see user stories sto_48, sto_49

**Comment by mvi-eea-sk** [comment]
For now, changing the dataset to private or deleting it in IC just disables the synchronization. The synchronized dataset in PC stays as it is.

**Comment by hanecak** [comment]
@OskarStoffan is right, publishers should typically follow sto_48 (#137) , sto_49 (#138).

But, delete is delete and might be handy in case of some fatal errors.

So delete of dataset in IC should be possible and should also delete the dataset in PC. @mvi-eea-sk , do you see a problem implementing this?

(because if yes, then only workaround is possible: ODN admin will take log in also into PC and delete dataset there too; note: PC has different admin account than IC - that's on purpose)

**Comment by mvi-eea-sk** [comment]
@hanecak it shouldn't be hard to implement

Note: its not possible to permanently delete (purge) dataset through api, only sysadmin can do that. it only changes its state to "deleted" so it can't be displayed and its not publicly accessible.

**Comment by Jan-Marcek** [comment]
There were same problem on the different line.
Fixed by previous commit

**Comment by hanecak** [comment]
OK, last commit (https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/commit/acd245530de6d095c3af80b628c0758413a66567) went into ODN 1.3.0, closing.
