### ISSUE TITLE
Single sign on error in UV.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#111]
I logged into IC and worked with it. For 3 hours browser was opened but was not clicked. Consequently I continue with work in IC. Everything was running, no session expired. Than I click at the dataset and tried to create new pipeline manually. UV was opened with CAS login (Not correct!) and after login I wasn't forwarded into canvas for editing pipeline, but at the tab Test (Not correct!).

**Comment by skrchnavy** [comment]
This is partially related to #95, user shall be logged in all system or nowhere, so this shall not happen.

**Comment by peterklimo** [comment]
@eea71 can you please retest it ? this was reported long time ago when the single sign out procedure was not correctly implemented in unifiedviews.
however sign out from IC as a reaction to sign out from other applications does still not work due to missing implementation of this feature (should be delivered by MC)
