### ISSUE TITLE
URL of dataset dont changing after TITLE is changed!

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#132]
I created dataset with Title = URL already existing. After SAVE err msg was rised.
![image](https://cloud.githubusercontent.com/assets/10993265/7878330/fa848d9e-05e5-11e5-8b6e-bc152092c2d1.png)

Consequently I chaged TITLE. Push SAVE. The same err msg was rised. URL stayed still the same, no chage was mad after editing TITLE. Is not OK.
![image](https://cloud.githubusercontent.com/assets/10993265/7878369/45c94920-05e6-11e5-998c-dfd8e90b4dc0.png)

**Comment by skrchnavy** [comment]
@mvi-eea-sk please provide feedback if this is bug or feature of CKAN

**Comment by mvi-eea-sk** [comment]
Hard to say if it's bug or not.
The error message (more or less) clearly says that you have to change the name / url. You don't have to change the title to make the formular valid.

On other side when you first time open the create dataset formular, the name / url is automatically generated / changed according to what the title was set / changed.

**Comment by mvi-eea-sk** [comment]
related to #62

**Comment by skrchnavy** [comment]
@OskarStoffan could you specify expected behaviour in proper user story? Then we can solve this issue as bug.

**Comment by hanecak** [comment]
@skrchnavy Current behaviour is as expected, i.e. URL stays same even after title change. And if the publishers chooses to, he can actually change it.

Why? Once dataset is created and URL assigned to it, we want that URL to stay unchanged, so that users can use it to link to dataset directly.

Given that CKAN lacks feature which would do a redirect from old URLs to current up-to-date URL, the next best thing is to discourage user from changing URL (by not doing automatic update of URL based on title change).

Once URL is changed without redirects, all the deep-links from 3rd party sites (FB, Twitter, blogs, etc.) to that particular dataset stop working. That would be bad.

**Comment by eea71** [comment]
I think there is a little bit misunderstandig of the problem I wrote. This situation is not about changing URL of existing DB record. But about process of new record creation (in the moment of form validation). In this situation there is not URL stored anywhere. All this problem is about how to correctly solve problem with creating URL of new record after validation error status.

**Comment by hanecak** [comment]
Aha, now I understand.

OK, CKAN is handling that situation in a way as shown in your screenshot, i.e. in case of collision with existing dataset user is expected to both:
1. update the title
2. update the URL

(i.e. once he updates the title, he no longer enjoys luxury of having the URL be regenerated for him)

Well, that's how upstream CKAN chose to handle this. So I'm closing this as "wont fix" for now.

If this will start to trouble more users, we'll raise this issue with upstream.
