### ISSUE TITLE
No validation of scheduling rules.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#224]
Today - 2.10.2015 I scheduled pipeline to august and september 2015? Is it ok?
![image](https://cloud.githubusercontent.com/assets/10993265/10246824/d02f10c2-6914-11e5-93ac-4f2d1b081fef.png)

**Comment by skrchnavy** [comment]
It is UnifiedViews Core issue, will be reported there

**Comment by hanecak** [comment]
In an attempt to clean-up our backlog, I'm closing this as "wont fix" given that bug is truly old (we're supporting only most recent minor release, i.e. as of ODN 1.2.5, we're supporting 1.2.x, not older).

Having said that, whoever is negatively affected by this again in the future, please reopen this.
