### ISSUE TITLE
It is possible to schedule pipeline non associated.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#225]
I disassociate pipeline. I click scheduler and I create rule for this pipeline. I was successful.
![image](https://cloud.githubusercontent.com/assets/10993265/10246924/7d303328-6915-11e5-85a0-4145b95dd506.png)

**Comment by hanecak** [comment]
This behaviour seems OK - user should be able to work with and schedule pipelines even if they are not associated with datasets.

Note: On the other hand, user would need to be careful, because if he's using *ToCkan loaders, those will fail (without association, they are not able to push data into ODN/InternalCatalog). But that's expected behaviour too.
